Implementation
valitydev/mayday pull request #2
Opened 2023-06-19 08:44 UTC by echerniak

2023-08-16 09:37 UTC, ex01tus requested changes

2023-08-16 09:37 UTC, ex01tus commented on README.md
> +Когда алертменеджер отправляет алерт, в качестве способа отправки используется [webhook](https://prometheus.io/docs/alerting/latest/configuration/#webhook_config), а в качестве адресата - сервис mayd
```suggestion
Когда алертменеджер отправляет алерт, в качестве способа отправки используется [webhook](https://prometheus.io/docs/alerting/latest/configuration/#webhook_config), а в качестве адресата - сервис mayday (вебхук прилетает в [контроллер](src/main/java/dev/vality/alerting/mayday/alertmanager/controller/WebhookController.java)). Mayday на основе содержимого вебхука определяет получателся алерта и "прокидывает" его дальше, предварительно преобразовав в нужный формат - в данный момент единственным получателем является сервис [alert-tg-bot](https://github.com/valitydev/alert-tg-bot).
```

2023-08-16 09:37 UTC, ex01tus commented on README.md
> +| `substitution_name` | Название переменной, в которое будет подставлятся значение, которое передал пользователь. Значение подставляется в поля `prometheus_query`, `alert_name_template`, `alert_notif
```suggestion
| `substitution_name` | Название переменной, в которое будет подставляться значение, которое передал пользователь. Значение подставляется в поля `prometheus_query`, `alert_name_template`, `alert_notification_template` описанные выше                                                                                        |
```

2023-08-21 06:04 UTC, karle0wne commented on README.md
> +| `parameters`                  | Массив параметров, которые должен задать пользователь, чтобы mayday смог создать алерт
```suggestion
| `parameters`                  | Карта с параметрами, которые должен задать пользователь, чтобы mayday смог создать алерт                                                                                                                                                                                |
```
мб так? семантически json это key value

2023-08-21 06:34 UTC, echerniak commented on README.md
> +| `parameters`                  | Массив параметров, которые должен задать пользователь, чтобы mayday смог создать алерт
Мне кажется массив корректнее. С одной стороны, каждый параметр это действительно key value, но сама конфигурация хранит именно массив объектов, каждый из которых описывает отдельный параметр:
```json
"parameters": [
    {
      "id": 1
    },
    {
      "id": 2
    }
```

2023-08-24 09:37 UTC, karle0wne commented on src/main/resources/application.yml
> +  prometheus-rule:
тут со сдвигами все нормально?

2023-08-24 11:40 UTC, echerniak commented on src/main/resources/application.yml
> +  prometheus-rule:
Да, тут скорее с именованием беда, но я не придумал ничего лучше.
`k8s.namespace` - тут прописывается неймспейс кубера, к которому будет подключаться клиент. Локально, например, это будет `default`, если не производить доп.настройку. У нас на стенде он "пустой" и его не нужно указывать. Поэтому в файле со свойствами выглядит немного странно

2023-10-20 12:50 UTC, ex01tus approved these changes

2023-10-20 13:23 UTC, merged