Adding a template for average_revenue_deviation
valitydev/mayday pull request #28
Opened 2024-09-02 17:59 UTC by Gretchen-z

2024-09-03 08:26 UTC, echerniak requested changes

2024-09-03 08:26 UTC, echerniak commented on src/main/resources/template/average_revenue_deviation.json
> +  "prometheus_query": "(sum_over_time(ebm_payments_amount{provider_id=~\"${provider_id}\",shop_id=~\"${shop_id}\",status=\"captured\",terminal_id=~\"${terminal_id}\",currency=~\"${currency}\",duratio
Запрос немного другой будет - `sum_over_time` тут не подойдет (всё потому что у нас несколько иначе пишутся эти метрики, они уже саггрегированы). 
Вместо него нужно везде в этом запросе использовать просто `sum` + убрать `[${aggr_period}]` и я бы убрал деление не экспоненту валюты - `scalar(10^ebm_currency_exponent{symbolic_code=~\"${currency}\"})`. Пользователь может ее не указать + надо тогда делить и в знаменателе/второй части запроса, иначе сейчас делим оборот в условных долларах на оборот в центах.

2024-09-03 08:26 UTC, echerniak commented on src/main/resources/template/average_revenue_deviation.json
> +  "alert_name_template": "Отклонение среднего оборота для провайдера '${provider_id}', терминала '${terminal_id}' и магазина '${shop_id}' с валютой '${currency}' за период: ${aggr_period} > среднего
Давай тут формулировку немного изменим:  "Оборот для провайдера ..... превышает `${threshold_factor}` среднего оборота за последние 30 дней"

2024-09-03 08:26 UTC, echerniak commented on src/main/resources/template/average_revenue_deviation.json
> +  "alert_notification_template": "Оборот за период '${aggr_period}' по провайдеру '${provider_id}', терминалу '${terminal_id}' и магазину '${shop_id}' с валютой '${currency}' превышает средний оборот
И тут по аналогии с комментом выше

2024-09-03 11:12 UTC, Gretchen-z commented on src/main/resources/template/average_revenue_deviation.json
> +  "prometheus_query": "(sum_over_time(ebm_payments_amount{provider_id=~\"${provider_id}\",shop_id=~\"${shop_id}\",status=\"captured\",terminal_id=~\"${terminal_id}\",currency=~\"${currency}\",duratio
исправила запрос

2024-09-03 11:12 UTC, Gretchen-z commented on src/main/resources/template/average_revenue_deviation.json
> +  "alert_name_template": "Отклонение среднего оборота для провайдера '${provider_id}', терминала '${terminal_id}' и магазина '${shop_id}' с валютой '${currency}' за период: ${aggr_period} > среднего
поменяла

2024-09-03 11:12 UTC, Gretchen-z commented on src/main/resources/template/average_revenue_deviation.json
> +  "alert_notification_template": "Оборот за период '${aggr_period}' по провайдеру '${provider_id}', терминалу '${terminal_id}' и магазину '${shop_id}' с валютой '${currency}' превышает средний оборот
поменяла

2024-09-03 12:21 UTC, echerniak approved these changes, later dismissed

2024-09-09 10:04 UTC, echerniak approved these changes

2024-09-09 10:04 UTC, merged